stages:
    - deploy
variables:
    GITLAB_URL: "ssh://git@45.149.78.59:22/peste.dev/ovisit-web.git"
    MAIN_PATH: "/opt/peste/web"
    PROJECT_PATH: "ovisit"
    ORIGIN: "development"
    
before_script:
  - echo "project path $MAIN_PATH/$PROJECT_PATH"
  - echo "origin $ORIGIN"
  - sudo chmod 666 /var/run/docker.sock
  - export CI=false

deploy-project:
    stage: deploy
    script:
        - pwd
        - sudo mkdir -p $MAIN_PATH
        - sudo chown -R gitlab-runner:root $MAIN_PATH/$PROJECT_PATH
        - if [ ! -d "$MAIN_PATH/$PROJECT_PATH" ]; then sh -c "cd $MAIN_PATH && sudo git clone $GITLAB_URL $PROJECT_PATH"; fi
        - cd $MAIN_PATH/$PROJECT_PATH
        - sudo git pull origin $ORIGIN
        - yarn install
        - yarn build
    only:
        - development
